/**
 * Traffic counting, kept deliberately small.
 *
 * She is losing her Bluehost stats the day the domain moves, because those are
 * generated by the server that hosts the site. This replaces the part of them
 * she actually reads: how many people came, and what they looked at.
 *
 * Design notes, because they are load bearing:
 *
 * 1. NO COOKIES, NO THIRD PARTY, NO IP ON DISK. A visitor is counted as a
 *    daily hash of address and user agent, salted with a secret and with the
 *    date itself. Tomorrow the same person hashes to something different, so
 *    the file cannot be used to follow anyone across days, and nothing
 *    identifying is ever written down. This is the same approach the
 *    cookieless analytics products use, and it is why the site needs no cookie
 *    banner for it.
 *
 * 2. ONE FILE PER DAY. content/analytics/YYYY-MM-DD.json, inside the volume, so
 *    history survives a redeploy exactly like her posts do. A day is a few
 *    kilobytes. Reading thirty of them to draw a card is nothing.
 *
 * 3. COUNTING NEVER BLOCKS A PAGE. Everything happens in memory and is flushed
 *    on a timer. If the disk write fails the visitor still gets their page;
 *    losing a count is not worth failing a request over.
 *
 * 4. PAGES ONLY. Assets, the editor, the API and the order pages are not
 *    traffic, and order URLs carry a session id that has no business here.
 *
 * Days are UTC, so a day never changes length underneath a chart.
 */
const crypto = require('crypto');
const fs = require('fs');
const fsp = require('fs/promises');
const path = require('path');

// Anything that announces itself as automated. Bots are most of the raw hits on
// a small site, and counting them would make every number a lie.
const BOT = new RegExp([
  'bot', 'crawl', 'spider', 'slurp', 'curl', 'wget', 'headless', 'phantom',
  'scrapy', 'python-requests', 'go-http', 'java/', 'okhttp', 'axios', 'httpx',
  'facebookexternalhit', 'whatsapp', 'telegrambot', 'discordbot', 'slackbot',
  'semrush', 'ahrefs', 'mj12', 'dotbot', 'petalbot', 'bytespider', 'gptbot',
  'ccbot', 'claudebot', 'perplexity', 'applebot', 'bingpreview', 'feedfetcher',
  'lighthouse', 'pingdom', 'uptime', 'monitor', 'preview', 'dataprovider',
].join('|'), 'i');

const pad = (n) => (n < 10 ? '0' : '') + n;
const dayOf = (d) => d.getUTCFullYear() + '-' + pad(d.getUTCMonth() + 1) + '-' + pad(d.getUTCDate());

/** Yesterday, the day before, and so on. Newest last. */
function lastDays(n, from) {
  const out = [];
  const base = from ? new Date(from) : new Date();
  for (let i = n - 1; i >= 0; i--) {
    const d = new Date(base.getTime() - i * 864e5);
    out.push(dayOf(d));
  }
  return out;
}

class Analytics {
  constructor(opts) {
    opts = opts || {};
    this.dir = path.join(opts.contentDir, 'analytics');
    fs.mkdirSync(this.dir, { recursive: true });

    // Rotating the salt daily is what stops the stored hashes from being
    // linkable over time. A restart changes it too, which at worst counts one
    // returning visitor twice in a day.
    this.salt = opts.salt || crypto.randomBytes(16).toString('hex');

    this.day = null;          // the day currently in memory
    this.dirty = false;
    this.MAX_SEEN = 50000;    // a ceiling so a bad day cannot grow without bound
    this.MAX_PAGES = 500;

    if (opts.autoFlush !== false) {
      this.timer = setInterval(() => { this.flush().catch(() => {}); }, 15000);
      if (this.timer.unref) this.timer.unref();
    }
  }

  /* ------------------------------------------------------------ recording -- */

  filePath(date) { return path.join(this.dir, date + '.json'); }

  /** The in-memory day, loaded from disk on first touch and at midnight. */
  _day(date) {
    if (this.day && this.day.date === date) return this.day;
    // Rolling over: write the finished day out before letting go of it.
    if (this.day && this.dirty) this._writeSync(this.day);

    let loaded = null;
    try { loaded = JSON.parse(fs.readFileSync(this.filePath(date), 'utf8')); }
    catch { /* first request of the day */ }

    this.day = {
      date: date,
      views: (loaded && loaded.views) || 0,
      pages: (loaded && loaded.pages) || {},
      referrers: (loaded && loaded.referrers) || {},
      seen: new Set((loaded && loaded.seen) || []),
    };
    this.dirty = false;
    return this.day;
  }

  /** A stable-for-today, useless-tomorrow fingerprint. Never stored raw. */
  _visitorKey(req, date) {
    const fwd = String(req.headers['x-forwarded-for'] || '').split(',')[0].trim();
    const ip = fwd || (req.socket && req.socket.remoteAddress) || '';
    const ua = String(req.headers['user-agent'] || '');
    return crypto.createHash('sha256')
      .update(this.salt + '|' + date + '|' + ip + '|' + ua)
      .digest('hex').slice(0, 12);
  }

  /** Where they came from, as a bare hostname. Never the full URL. */
  _referrer(req, host) {
    const raw = req.headers.referer || req.headers.referrer;
    if (!raw) return 'direct';
    let h;
    try { h = new URL(String(raw)).hostname.replace(/^www\./, ''); }
    catch { return 'direct'; }
    if (!h) return 'direct';
    if (host && h === String(host).replace(/^www\./, '').split(':')[0]) return 'direct';
    return h.slice(0, 80);
  }

  /**
   * Count one page view. Returns false when the request was ignored, which is
   * what the tests assert on.
   */
  record(req, pathname) {
    const ua = String(req.headers['user-agent'] || '');
    if (!ua || BOT.test(ua)) return false;
    // No user agent at all is a script, not a person.

    const date = dayOf(new Date());
    const day = this._day(date);

    day.views++;

    const key = this._visitorKey(req, date);
    if (!day.seen.has(key) && day.seen.size < this.MAX_SEEN) day.seen.add(key);

    const p = String(pathname || '/').slice(0, 200);
    if (day.pages[p] !== undefined || Object.keys(day.pages).length < this.MAX_PAGES) {
      day.pages[p] = (day.pages[p] || 0) + 1;
    }

    const r = this._referrer(req, req.headers.host);
    if (day.referrers[r] !== undefined || Object.keys(day.referrers).length < this.MAX_PAGES) {
      day.referrers[r] = (day.referrers[r] || 0) + 1;
    }

    this.dirty = true;
    return true;
  }

  /* ------------------------------------------------------------- storage -- */

  _serialise(day) {
    return JSON.stringify({
      date: day.date,
      views: day.views,
      visitors: day.seen.size,
      pages: day.pages,
      referrers: day.referrers,
      // Kept so a restart does not count the same person again. Salted with a
      // secret and with the date, so it identifies nobody and links to nothing.
      seen: Array.from(day.seen),
    }) + '\n';
  }

  _writeSync(day) {
    try { fs.writeFileSync(this.filePath(day.date), this._serialise(day)); }
    catch { /* a lost count is not worth an exception */ }
  }

  async flush() {
    if (!this.dirty || !this.day) return false;
    const day = this.day;
    this.dirty = false;
    try { await fsp.writeFile(this.filePath(day.date), this._serialise(day)); return true; }
    catch { return false; }
  }

  /* ------------------------------------------------------------ reporting -- */

  async readDay(date) {
    // The day in memory is ahead of the file, so prefer it.
    if (this.day && this.day.date === date) {
      return {
        date: date, views: this.day.views, visitors: this.day.seen.size,
        pages: this.day.pages, referrers: this.day.referrers,
      };
    }
    try {
      const d = JSON.parse(await fsp.readFile(this.filePath(date), 'utf8'));
      return {
        date: date, views: d.views || 0, visitors: d.visitors || 0,
        pages: d.pages || {}, referrers: d.referrers || {},
      };
    } catch {
      return { date: date, views: 0, visitors: 0, pages: {}, referrers: {} };
    }
  }

  /**
   * Everything the dashboard needs, in one pass.
   *
   * `visitors` is summed across days, so someone who comes back on three days
   * counts three times. Over a month that is the honest number to show: it is
   * "visits", not "people", and the card says so.
   */
  async summary(days) {
    days = Math.max(1, Math.min(365, days || 30));
    const dates = lastDays(days);
    const perDay = [];
    const pages = {}, referrers = {};
    let views = 0, visitors = 0;

    for (const date of dates) {
      const d = await this.readDay(date);
      perDay.push({ date: d.date, views: d.views, visitors: d.visitors });
      views += d.views;
      visitors += d.visitors;
      for (const k of Object.keys(d.pages)) pages[k] = (pages[k] || 0) + d.pages[k];
      for (const k of Object.keys(d.referrers)) referrers[k] = (referrers[k] || 0) + d.referrers[k];
    }

    const top = (obj, n) => Object.keys(obj)
      .map(k => ({ name: k, count: obj[k] }))
      .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name))
      .slice(0, n);

    // The same window immediately before this one, so the card can say whether
    // things are going up. Without it a number is just a number.
    const prevDates = lastDays(days, new Date(Date.now() - days * 864e5));
    let prevViews = 0, prevVisitors = 0;
    for (const date of prevDates) {
      const d = await this.readDay(date);
      prevViews += d.views;
      prevVisitors += d.visitors;
    }

    return {
      days: days,
      from: dates[0],
      to: dates[dates.length - 1],
      views: views,
      visitors: visitors,
      previous: { views: prevViews, visitors: prevVisitors },
      perDay: perDay,
      topPages: top(pages, 15),
      topReferrers: top(referrers, 10),
    };
  }

  /** Days on record, oldest first. Used to say "since 3 March". */
  async since() {
    try {
      const f = (await fsp.readdir(this.dir))
        .filter(x => /^\d{4}-\d{2}-\d{2}\.json$/.test(x)).sort();
      return f.length ? f[0].replace('.json', '') : null;
    } catch { return null; }
  }

  /** Drop files older than `keepDays`. Called on boot; nothing else needs it. */
  async prune(keepDays) {
    const cutoff = dayOf(new Date(Date.now() - (keepDays || 400) * 864e5));
    let removed = 0;
    try {
      for (const f of await fsp.readdir(this.dir)) {
        if (!/^\d{4}-\d{2}-\d{2}\.json$/.test(f)) continue;
        if (f.replace('.json', '') < cutoff) {
          await fsp.unlink(path.join(this.dir, f)).catch(() => {});
          removed++;
        }
      }
    } catch { /* nothing to prune */ }
    return removed;
  }
}

module.exports = { Analytics, dayOf, lastDays, BOT };
